/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bautiweirdMoreTriangles.glb 
*/

import React, { useState, useEffect } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import AboutModelGLTF from "@/types/model";
import Annotation from "./Annotation";

export function AboutModel() {
  const { angle, rotAbout } = useControls({
    angle: 0,
    rotAbout: [0, 0, 0],
  });

  const [hover, setHover] = useState(false);

  const { nodes, materials } = useGLTF(
    "/bautiModel.glb"
  ) as unknown as AboutModelGLTF;
  return (
    <group
      dispose={null}
      position={[-0.02, 0.08, 0]}
      rotation={[-0.51, -0.26, 0]}
      scale={0.7}
      onPointerOver={() => setHover(true)}
      onPointerLeave={() => setHover(false)}
    >
      <mesh
        geometry={nodes.tmpsj0p995tply001.geometry}
        material={materials["Material_0.002"]}
        position={[0, 0, 0]}
        castShadow
      >
        {hover && <Outlines thickness={1.1} color="red" />}
      </mesh>
      {hover && (
        <Annotation position={[0, 1.2, 0]} rotation={[-0.2, -0.2, -0.3]}>
          <span>About me</span>
        </Annotation>
      )}
    </group>
  );
}

useGLTF.preload("/bautiModel.glb");
