/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bautiweirdMoreTriangles.glb 
*/

import React, { useState } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import AboutModelGLTF from "@/types/model";
import Annotation from "./Annotation";

import { useSectionStore } from "@/utils/Utils";

const ABOUT_POSITION: [number, number, number] = [-0.02, 0.08, 0];
const ABOUT_ROTATION: [number, number, number] = [-0.51, -0.26, 0];
const ABOUT_SCALE = 0.7;
const ABOUT_MESH_POSITION: [number, number, number] = [0, 0, 0];

export function AboutModel() {
  const [hover, setHover] = useState(false);

  const setSectionClicked = useSectionStore((s) => s.setSectionClicked);

  const { nodes, materials } = useGLTF(
    "/bautiModel.glb"
  ) as unknown as AboutModelGLTF;
  return (
    <group
      dispose={null}
      position={ABOUT_POSITION}
      rotation={ABOUT_ROTATION}
      scale={ABOUT_SCALE}
      onPointerOver={(e) => {
        e.stopPropagation();
        setHover(true);
      }}
      onPointerLeave={(e) => {
        e.stopPropagation();
        setHover(false);
      }}
      onClick={(event) => {
        event.stopPropagation();
        setSectionClicked("About", true);
      }}
    >
      <mesh
        geometry={nodes.tmpsj0p995tply001.geometry}
        material={materials["Material_0.002"]}
        position={ABOUT_MESH_POSITION}
        castShadow
        receiveShadow
      >
        {hover && <Outlines thickness={1.1} color="white" />}
      </mesh>
      {hover && (
        <Annotation position={[0, 1.2, 0]} rotation={[-0.2, -0.2, -0.3]}>
          <span className="text-shadow-2xl">About me</span>
        </Annotation>
      )}
    </group>
  );
}

/**
 * Invisible copy of the model's mesh (same transforms and geometry) used by
 * the lazily loaded physics world to build the head's convex hull collider.
 */
export function AboutModelColliderShape() {
  const { nodes } = useGLTF("/bautiModel.glb") as unknown as AboutModelGLTF;
  return (
    <group
      dispose={null}
      position={ABOUT_POSITION}
      rotation={ABOUT_ROTATION}
      scale={ABOUT_SCALE}
    >
      <mesh
        geometry={nodes.tmpsj0p995tply001.geometry}
        position={ABOUT_MESH_POSITION}
      >
        <meshBasicMaterial visible={false} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/bautiModel.glb");
