/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bautiweirdMoreTriangles.glb 
*/

import React, { useState } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import AboutModelGLTF from "@/types/model";
import Annotation from "./Annotation";

import { useSectionStore } from "@/utils/Utils";

export function AboutModel() {
  const [hover, setHover] = useState(false);

  const { setSectionClicked } = useSectionStore();

  const { nodes, materials } = useGLTF(
    "/bautiModel.glb"
  ) as unknown as AboutModelGLTF;
  return (
    <group
      dispose={null}
      position={[-0.02, 0.08, 0]}
      rotation={[-0.51, -0.26, 0]}
      scale={0.7}
      onPointerOver={(e) => {
        e.stopPropagation();
        setHover(true);
      }}
      onPointerLeave={(e) => {
        e.stopPropagation();
        setHover(false);
      }}
      onClick={(event) => {
        event.stopPropagation();
        setSectionClicked("About", true);
      }}
    >
      <mesh
        geometry={nodes.tmpsj0p995tply001.geometry}
        material={materials["Material_0.002"]}
        position={[0, 0, 0]}
        castShadow
      >
        {hover && <Outlines thickness={1.1} color="white" />}
      </mesh>
      {hover && (
        <Annotation position={[0, 1.2, 0]} rotation={[-0.2, -0.2, -0.3]}>
          <span className="text-shadow-2xl">About me</span>
        </Annotation>
      )}
    </group>
  );
}

useGLTF.preload("/bautiModel.glb");
