/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/box2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export function Box2Model(props) {
  const { rotationB, positionB } = useControls({
    positionB: [-0.065, 0, 0.443],
    rotationB: [-Math.PI / 2, 0, 2.22],
  });
  const { nodes, materials } = useGLTF("/box2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Box_2-b001_Boxes_0"].geometry}
        material={materials.Boxes}
        scale={10}
        position={positionB}
        rotation={rotationB}
      />
    </group>
  );
}

useGLTF.preload("/box2.glb");
