/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DrewA (https://sketchfab.com/DrewA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/diploma-frame-9030281e7df84ca8b544c2acaa3688a0
Title: Diploma Frame
*/
import * as THREE from "three";
import React, { ComponentProps, useState } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useClearDiplomasStore } from "@/utils/Utils";

type GLTFResult = GLTF & {
  nodes: {
    pCube1_lambert1_0: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
  };
};

export function Diploma(props: ComponentProps<"group">) {
  const { nodes, materials } = useGLTF("/diploma.glb") as unknown as GLTFResult;
  const { setClearDiplomas } = useClearDiplomasStore();
  const [hover, setHover] = useState(false);

  const hoverBox = () => {
    document.body.style.cursor = "pointer";
    setHover(true);
  };

  const hoverLeave = () => {
    document.body.style.cursor = "grab";
    setHover(false);
  };

  const onClick = () => {
    setClearDiplomas(true);
  };


  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.242, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            onClick={onClick}
            onPointerOver={hoverBox}
            onPointerLeave={hoverLeave}
            castShadow
            receiveShadow
            geometry={nodes.pCube1_lambert1_0.geometry}
            material={materials.lambert1}
            scale={[0.663, 0.061, 0.802]}
          >
            {hover && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/diploma.glb");
