/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mail.glb -t 
Author: Mylom (https://sketchfab.com/Mylom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-mail-letter-e6b3a25ed9234c5fa8fa65b1a76262c0
Title: low-poly-mail-letter
*/

import React, { ComponentProps } from "react";
import { useGLTF } from "@react-three/drei";
import MailGltfResult from "@/types/model";
import { Outlines } from "@react-three/drei";

interface MailModelProps extends ComponentProps<"group"> {
  isHovered?: boolean;
}

export function MailModel({ isHovered = false, ...props }: MailModelProps) {
  const { nodes, materials } = useGLTF(
    "/mail.glb"
  ) as unknown as MailGltfResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group
          position={[0, 0, -0.052]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[1, 1, 0.791]}
        >
          <mesh
            geometry={nodes["Letter_02_-_Default_0"].geometry}
            material={materials["02_-_Default"]}
          />
          <mesh
            geometry={nodes["Letter_01_-_Default_0"].geometry}
            material={materials["01_-_Default"]}
          >
            {isHovered && (
              <Outlines
                castShadow={false}
                thickness={0.6}
                color="white"
                angle={0}
                scale={1.02}
              />
            )}
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mail.glb");
