/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/portfolio.glb 
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import useCameraStore from "@/Utils";

export function PorfolioModel(props) {
  const { rota, posa } = useControls({
    posa: [4.2, 0, -2.3],
    rota: [0, 5.4, 0],
  });

  const [hover, setHover] = useState(false);

  const { setCameraZoomed, isTransitioning, setTransitioning } =
    useCameraStore();

  const hoverBox = () => {
    if (isTransitioning) return;
    setHover(true);

    document.body.style.cursor = "pointer";
    setCameraZoomed(true);
  };

  const hoverLeave = () => {
    if (isTransitioning) return;
    setHover(false);

    document.body.style.cursor = "grab";
    setCameraZoomed(false);
  };

  const { nodes, materials } = useGLTF("/portfolio.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={11}
      position={[4, 0, -1.7]}
      rotation={[0, 5.4, 0]}
      onPointerOver={() => hoverBox()}
      onPointerLeave={() => hoverLeave()}
    >
      <group
        position={[-0.02, 0.018, 0.471]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.0038}
      >
        <group
          position={[-12.118, 6.028, 5.83]}
          rotation={[1.698, 0.352, 0.692]}
        >
          <mesh
            geometry={nodes.pPlane3_lambert4_0.geometry}
            material={materials.lambert4}
            position={[-8.273, 4.847, -0.877]}
            rotation={[1.231, 0.197, 0.237]}
            scale={[1, 1, 1.044]}
          />
        </group>
      </group>
      <group
        position={[0.055, -0.117, 0.5]}
        rotation={[-3.135, 0.523, 3.132]}
        scale={0.008}
      >
        <group position={[1.237, 0.03, -3.857]}>
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.VoxMaterial_250}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.VoxMaterial_251}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.VoxMaterial_252}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.VoxMaterial_225}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.VoxMaterial_227}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.VoxMaterial_229}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.VoxMaterial_231}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.VoxMaterial_249}
          />
        </group>
      </group>

      <mesh
        geometry={nodes["Box_1-b_Boxes_0"].geometry}
        material={materials.Boxes}
        position={[-0.065, 0, 0.443]}
        rotation={[-Math.PI / 2, 0, 0]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials["cover.117"]}
        position={[-0.064, 0.08, 0.307]}
        rotation={[1.32, 0.09, -0.01]}
        scale={0.55}
      />
    </group>
  );
}

useGLTF.preload("/portfolio.glb");
