/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/portfolio.glb 
*/

import React, { useState, useMemo } from "react";
import { Outlines, useGLTF, useTexture } from "@react-three/drei";
import { useCameraStore, useSectionStore } from "@/utils/Utils";

import PorfolioGLTF from "@/types/model";
import { MailModel } from "./Mail";
import Annotation from "./Annotation";
import { DoubleSide } from "three";
import type { ColliderBody, ColliderBodyProps } from "./physics/types";

const PORTFOLIO_SCALE = 11;
const PORTFOLIO_POSITION: [number, number, number] = [4, 0, -1.7];
const PORTFOLIO_ROTATION: [number, number, number] = [0, 5.4, 0];

const BOX_BASE_POSITION: [number, number, number] = [-0.065, 0, 0.443];
const BOX_BASE_ROTATION: [number, number, number] = [-Math.PI / 2, 0, 0];
const WALL_THICKNESS = 0.005;
const WALL_OFFSET_Y = 0.05; // Moves the wall colliders up
const WALLS_POSITION: [number, number, number] = [
  BOX_BASE_POSITION[0],
  BOX_BASE_POSITION[1] + WALL_OFFSET_Y,
  BOX_BASE_POSITION[2],
];

// Black plane behind the vinyl cover: hover target + collider.
const VINYL_BACK_POSITION: [number, number, number] = [-0.061, 0.079, 0.319];
const VINYL_BACK_ROTATION: [number, number, number] = [-0.17, 3.14, 0];
const VINYL_ARGS: [number, number] = [0.15, 0.15];

function NoBody({ children }: ColliderBodyProps) {
  return <>{children}</>;
}

/**
 * Invisible box walls. The visual model renders them as plain meshes (they
 * are raycast targets for the box hover); the lazily loaded physics world
 * renders them wrapped in fixed RigidBodies. One component keeps both copies
 * identical.
 */
function BoxWalls({ Body = NoBody }: { Body?: ColliderBody }) {
  const { nodes } = useGLTF("/portfolio.glb") as unknown as PorfolioGLTF;

  const boxDimensions = useMemo(() => {
    const geometry = nodes["Box_1-b_Boxes_0"].geometry;
    geometry.computeBoundingBox();
    const box = geometry.boundingBox!;

    return {
      width: box.max.x - box.min.x,
      height: box.max.y - box.min.y,
      depth: box.max.z - box.min.z,
    };
  }, [nodes]);

  return (
    <group position={WALLS_POSITION} rotation={BOX_BASE_ROTATION}>
      {/* Bottom wall */}
      <Body>
        <mesh position={[0, -boxDimensions.height / 2.2, 0]}>
          <boxGeometry
            args={[boxDimensions.width, WALL_THICKNESS, boxDimensions.depth]}
          />
          <meshStandardMaterial visible={false} />
        </mesh>
      </Body>

      <Body>
        <mesh position={[0, boxDimensions.height / 2.2, 0]}>
          <boxGeometry
            args={[boxDimensions.width, WALL_THICKNESS, boxDimensions.depth]}
          />
          <meshStandardMaterial visible={false} />
        </mesh>
      </Body>

      {/* Front wall intentionally omitted (open box) */}

      {/* Back wall */}
      <Body>
        <mesh position={[0, 0, -boxDimensions.depth / 2.2]}>
          <boxGeometry
            args={[boxDimensions.width, boxDimensions.height, WALL_THICKNESS]}
          />
          <meshStandardMaterial visible={false} />
        </mesh>
      </Body>

      {/* Left wall */}
      <Body>
        <mesh position={[-boxDimensions.width / 2.2, 0, 0]}>
          <boxGeometry
            args={[WALL_THICKNESS, boxDimensions.height, boxDimensions.depth]}
          />
          <meshStandardMaterial visible={false} />
        </mesh>
      </Body>

      {/* Right wall */}
      <Body>
        <mesh position={[boxDimensions.width / 2.2, 0, 0]}>
          <boxGeometry
            args={[WALL_THICKNESS, boxDimensions.height, boxDimensions.depth]}
          />
          <meshStandardMaterial visible={false} />
        </mesh>
      </Body>
    </group>
  );
}

/**
 * Collider shapes of the portfolio box (walls + vinyl) under the same
 * transforms as PorfolioModel. Rendered only by the lazily loaded physics
 * world.
 */
export function PortfolioColliderShapes({ Body }: { Body: ColliderBody }) {
  return (
    <group
      dispose={null}
      scale={PORTFOLIO_SCALE}
      position={PORTFOLIO_POSITION}
      rotation={PORTFOLIO_ROTATION}
    >
      <BoxWalls Body={Body} />
      <group>
        <Body>
          <mesh position={VINYL_BACK_POSITION} rotation={VINYL_BACK_ROTATION}>
            <planeGeometry args={VINYL_ARGS} />
            <meshBasicMaterial visible={false} />
          </mesh>
        </Body>
      </group>
    </group>
  );
}

export function PorfolioModel() {
  // const { rota, posa } = useControls({
  //   posa: [22.4, 18, 9.3],
  //   rota: [0, 5, 0],
  // });

  const [hoverShovel, setHoverShovel] = useState<boolean>(false);
  // const [hoverCard, setHoverCard] = useState<boolean>(false);
  const [hoverVinyl, setHoverVinyl] = useState<boolean>(false);
  const [hoverMail, setHoverMail] = useState<boolean>(false);

  const cameraZoomed = useCameraStore((s) => s.cameraZoomed);
  const setCameraZoomed = useCameraStore((s) => s.setCameraZoomed);
  const isTransitioning = useCameraStore((s) => s.isTransitioning);
  const setSectionClicked = useSectionStore((s) => s.setSectionClicked);

  const [toolTexture] = useTexture(["/images/tool3.png"]);

  const hoverBox = () => {
    if (isTransitioning) return;
    if (!cameraZoomed) {
      document.body.style.cursor = "pointer";
      setCameraZoomed(true);
    }
  };

  const hoverLeave = () => {
    if (isTransitioning) return;
    if (cameraZoomed) {
      document.body.style.cursor = "grab";
      setCameraZoomed(false);
    }
  };

  const { nodes, materials } = useGLTF(
    "/portfolio.glb"
  ) as unknown as PorfolioGLTF;

  return (
    <group
      dispose={null}
      scale={PORTFOLIO_SCALE}
      position={PORTFOLIO_POSITION}
      rotation={PORTFOLIO_ROTATION}
      onPointerOver={() => hoverBox()}
      onPointerMissed={() => hoverLeave()}
    >
      {/* <group
        position={[-0.02, 0.018, 0.471]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.0038}
      >
        <group
          position={[-12.118, 6.028, 5.83]}
          rotation={[1.698, 0.352, 0.692]}
          onPointerEnter={() => setHoverCard(true)}
          onPointerLeave={() => setHoverCard(false)}
        >
          <mesh
            geometry={nodes.pPlane3_lambert4_0.geometry}
            material={materials.lambert4}
            position={[-8.273, 4.847, -0.877]}
            rotation={[1.231, 0.197, 0.237]}
            scale={[1, 1, 1.044]}
          >
            {hoverCard && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
        </group>
      </group> */}
      <group
        position={[-0.09, -0.11, 0.59]}
        rotation={[-3.17, 1.5, 3.13]}
        scale={0.008}
        onPointerEnter={() => setHoverShovel(true)}
        onPointerLeave={() => setHoverShovel(false)}
        onClick={() => setSectionClicked("Work", true)}
      >
        <group position={[1.237, 0.03, -3.857]}>
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.VoxMaterial_250}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.VoxMaterial_251}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.VoxMaterial_252}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>

          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.VoxMaterial_225}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.VoxMaterial_227}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.VoxMaterial_229}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.VoxMaterial_231}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.VoxMaterial_249}
          >
            {hoverShovel && (
              <Outlines castShadow={false} thickness={1.1} color="white" />
            )}
          </mesh>
          {hoverShovel && (
            <Annotation
              position={[22.4, 18, 9.3]}
              rotation={[0, 5, 0]}
              scale={10}
            >
              <span>Work</span>
            </Annotation>
          )}
        </group>
      </group>

      {/* Visual mesh (the actual box you see) - stays in original position */}
      <group position={BOX_BASE_POSITION} rotation={BOX_BASE_ROTATION}>
        <mesh
          geometry={nodes["Box_1-b_Boxes_0"].geometry}
          material={materials.Boxes}
          castShadow
          receiveShadow
        />
      </group>

      {/* Invisible walls; their colliders live in the lazy physics world */}
      <BoxWalls />

      <group>
        <mesh
          position={VINYL_BACK_POSITION}
          rotation={VINYL_BACK_ROTATION}
          onPointerEnter={() => setHoverVinyl(true)}
          onPointerLeave={() => setHoverVinyl(false)}
        >
          <planeGeometry args={VINYL_ARGS} />
          <meshStandardMaterial color={"black"} side={DoubleSide} />
        </mesh>
        {hoverVinyl && (
          <Annotation scale={0.1} position={[-0.07, 0.15, 0.27]}>
            <span>Projects</span>
          </Annotation>
        )}
      </group>
      <mesh
        position={[-0.055, 0.079, 0.33]}
        rotation={[-0.26, 0, 0]}
        scale={0.99}
        onPointerEnter={() => setHoverVinyl(true)}
        onPointerLeave={() => setHoverVinyl(false)}
        onClick={() => {
          setSectionClicked("Projects", true);
        }}
      >
        <planeGeometry args={VINYL_ARGS} />
        <meshStandardMaterial map={toolTexture} side={DoubleSide} />
        {hoverVinyl && (
          <Outlines
            castShadow={false}
            thickness={0.5}
            color="white"
            angle={0}
            rotation={[0, Math.PI, 0]}
            scale={1.02}
          />
        )}
      </mesh>
      <group>
        <MailModel
          isHovered={hoverMail}
          scale={0.02}
          position={[-0.02, 0.04, 0.35]}
          rotation={[-0.22, 0.13, 45.52]}
          onPointerEnter={(e) => {
            e.stopPropagation();
            setHoverMail(true);
          }}
          onPointerLeave={(e) => {
            e.stopPropagation();
            setHoverMail(false);
          }}
          onClick={(e) => {
            e.stopPropagation();
            setSectionClicked("Contact", true);
          }}
        />
        {hoverMail && (
          <Annotation
            scale={0.05}
            position={[-0.017, 0.09, 0.34]}
            rotation={[-0.29, 0.16, -0.01]}
          >
            <span>Contact</span>
          </Annotation>
        )}
      </group>
    </group>
  );
}

useGLTF.preload("/portfolio.glb");
